version: "3.8"
services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    volumes:
      - ./data:/data/db

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "80:80"
    depends_on:
      - mongoDB
    volumes:
      - logs:/app/Logs
      - ./Backend:/server
      - /app/node_modules

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
    environment:
      - REACT_APP_PROXY=http://localhost:80
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: